#!/bin/env bash

echo
echo "========Chrony sources==========="
sudo chronyc sources
echo
echo "========Chrony sources stats==========="
sudo chronyc sourcestats
echo
echo "========Chrony offsets==========="
./survDateOffset.py
echo
echo "========bme280==========="
python3 -c "from lib.bme280_lib import readBME280All; temp, press, hum = readBME280All(); print(f'Temp: {temp:.2f}°C, Press: {press:.2f}hPa, Hum: {hum:.2f}%')"
echo "========================="

